config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    collection do
      get :settings
      get :preferences
    end
  end

  resources :charities do
    resources :posts, only: [:new, :create]
  end

  resources :comments, only: [ :create, :update, :destroy]
  resources :donations, only: [ :create]
  resources :follows, only: [ :create, :update]
  resources :likes, only: [ :create, :update]
  resources :posts, only: [ :new, :create, :edit, :update, :index]
  resources :ratings, only: [ :create, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charity.rb
class Charity < ApplicationRecord
  belongs_to :user
  has_many :donations
  has_many :follows
  has_many :ratings
  has_many :posts
  validates :name, presence: true, uniqueness: true
  mount_uploader :photo, PhotoUploader
  has_many :charity_themes, through: :charity_theme_relations
  has_many :charity_types, through: :charity_type_relations
end

app/models/charity_theme.rb
class CharityTheme < ApplicationRecord
  has_many :charity_theme_relations
  has_many :charity_theme_preferences
  has_many :charities, through: :charity_theme_relations
  has_many :users, through: :charity_theme_preferences
end

app/models/charity_theme_relation.rb
class CharityThemeRelation < ApplicationRecord
  belongs_to :charity
  belongs_to :charity_theme
end

app/models/charity_type.rb
class CharityType < ApplicationRecord
  has_many :charity_type_relations
  has_many :charity_type_preferences
  has_many :charities, through: :charity_type_relations
  has_many :users, through: :charity_type_preferences
end

app/models/charity_type_preference.rb
class CharityTypePreference < ApplicationRecord
  belongs_to :user
  belongs_to :charity_type
end

app/models/charity_type_relation.rb
class CharityTypeRelation < ApplicationRecord
  belongs_to :charity
  belongs_to :charity_type
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :content, presence: true
end

app/models/controller.rb
class Controller < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :user
  belongs_to :charity
  validates :credit, presence: true
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :user
  belongs_to :charity

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :charity
  mount_uploader :photo, PhotoUploader
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :charity
  validates :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[facebook]
  has_many :donations
  has_many :follows
  has_many :ratings
  has_many :likes
  has_many :comments
  mount_uploader :photo, PhotoUploader
  has_many :charity_type_preferences
  has_many :charity_theme_preferences
  has_many :charity_types, through: :charity_type_preferences
  has_many :charity_themes, through: :charity_theme_preferences

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name   # assuming the user model has a name
      user.photo = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
      user.save!
    end
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new()
    @charity = Charity.find(params)
  end

  def create
    @post = Post.new(post_params)
    @charity = Charity.find(params[:charity_id])
    @post.charity = @charity
    @post.save
    redirect_to charity_path(@charity)
  end

  private

  def post_params
    params.require(:post).permit(:content, :photo)
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def settings
    @user = current_user
    @users = User.all
    @charities = Charity.all
  end

  def preferences
    @themes = CharityTheme.all
    @types = CharityType.all
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    @user.save
    redirect_to posts_path
  end

  private

  def user_params
    params.require(:user).permit(:charity_theme_ids => [], :charity_type_ids => [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/users/preferences.html.erb
<div class="pigeon-container-preferences">

  <%= form_for(@user) do |f| %>

    <div class="preferences-flex">
      <h2 class="preferences-main-header">User preferences</h2>

      <div class="preferences-actions">
        <%= link_to posts_path do %>
          <div class="pigeon-button-gray pigeon-button-large pigeon-button-width">Skip</div>
        <% end %>
        <div class="actions">
          <%= f.submit "confirm", :class => "pigeon-button-blue pigeon-button-submit pigeon-button-width"  %>
        </div>
      </div>
    </div>

    <div class="preferences-variable-flex">
      <div class="preferences-box">
        <h3 class="pigeon-preferences-header">Organizations</h3>
        <div class="preferences-field">
          <%= hidden_field_tag "user[charity_type_ids][]", nil %>
          <% @types.each do |type| %>
            <label class="preferences-check-container">
              <%= check_box_tag "user[charity_type_ids][]", type.id, @user.charity_type_ids.include?(type.id), id: dom_id(type) %>
              <span class="checkmark"></span>
              <%= label_tag dom_id(type), type.name, :class => "preferences-check-name" %>
            </label>
          <% end %>
        </div>
      </div>

      <div class="references-box">
        <h3 class="pigeon-preferences-header">Social topics</h3>
        <div class="preferences-field">
          <%= hidden_field_tag "user[charity_theme_ids][]", nil %>
          <% @themes.each do |theme| %>
            <label class="preferences-check-container">
              <%= check_box_tag "user[charity_theme_ids][]", theme.id, @user.charity_theme_ids.include?(theme.id), id: dom_id(theme) %>
              <span class="checkmark"></span>
              <%= label_tag dom_id(theme), theme.name, :class => "preferences-check-name" %><br>
            </label>
          <% end %>
        </div>
      </div>
    </div>
    <div class="preferences-flex-center">
      <div class="actions">
        <%= f.submit "confirm", :class => "pigeon-button-blue pigeon-button-submit pigeon-button-width"  %>
      </div>
    </div>
  <% end %>
</div>




<!-- <div class="pigeon-container-preferences">
  <h2>Social topics</h2>
  <%= simple_form_for @user do |f| %>
  <div class="preferences-check-container">
    <%= f.association :charity_types, as: :check_boxes, item_wrapper_class: 'preferences-check-item' , :input_html => { :class => "preferences-checkbox" }%>
    <%= f.association :charity_themes, as: :check_boxes, item_wrapper_class: 'preferences-check-item' , :input_html => { :class => "preferences-checkbox" }%>
    <%= f.button :submit, "Proceed", class: "pigeon-button-submit pigeon-button-blue"  %>
  </div>
  <% end %>
</div> -->

app/views/users/profile.html.erb
<div class="pigeon-container-profile">
  <div class="charity-profile-header">
    <div class="charity-profile-profile">
      <div class="charity-profile-avatar">
        <%= cl_image_tag @user.photo, crop: :fill, class: "charity-avatar-large" %>
      </div>
      <div class="charity-profile-title">
        <p class="charity-profile-category invisible">invisible</p>
        <h3 class="charity-profile-name"><%= @user.first_name %> <%= @user.last_name %></h3>
        <p class="charity-profile-category invisible">invisible</p>
      </div>
    </div>
    <div class="charity-profile-followers-display">
      <i class="fas fa-dove charity-profile-follower-item"></i>
      <div class="charity-profile-followers">1,500</div>
    </div>
  </div>
  <div class="charity-profile-action">
    <div class="pigeon-button-large pigeon-button-blue" id="charity-profile-button-offset">Donate</div>
    <div class="pigeon-button-large pigeon-button-gray" id="charity-profile-button-offset">Follow</div>
  </div>
  <div class="charity-tabs">
    <a class="charity-tab active" id="charity-posts-tab" href="#">
      <p>Activity</p>
    </a>
    <a class="charity-tab" id="charity-about-tab" href="#">
      <p>Following</p>
    </a>
    <a class="charity-tab" id="charity-contact-tab" href="#">
      <p>Followers</p>
    </a>
  </div>
  <div class="charity-pages-container">

  </div>
</div>

app/views/users/settings.html.erb
<div class="pigeon-container-settings">
  <h3 class="pigeon-settings-header">Settings</h3>
    <div class="pigeon-settings-devider">
      <div class="pigeon-settings-container">
        <div class="pigeon-settings-title">
          <i class="fas fa-hand-holding-heart settings-credit-icon"></i>
          <div>Credits</div>
        </div>
        <div class="settings-flex">
          <div class="settings-credit-display pigeon-button-width">1,500</div>
          <div class="pigeon-button-blue pigeon-button-large pigeon-button-width">Buy</div>
        </div>
      </div>
    </div>
    <div class="pigeon-settings-devider">
      <div class="pigeon-settings-container">
        <div class="pigeon-settings-title">
          <i class="fas fa-cog settings-credit-icon"></i>
          <div>Change preferences</div>
        </div>
        <div class="settings-flex">
          <%= link_to preferences_users_path do %>
            <div class="pigeon-button-blue pigeon-button-large pigeon-button-width"> Edit </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="pigeon-settings-devider">
      <div class="pigeon-settings-container">
        <div class="pigeon-settings-title">
          <i class="fas fa-dove settings-credit-icon"></i>
          <div>Follow NGOs and charities</div>
        </div>
        <div class="settings-flex">
          <%= link_to charities_path do %>
            <div class="pigeon-button-blue pigeon-button-large pigeon-button-width">Search</div>
          <% end %>
        </div>
      </div>
      <div class="settings-units-container">
        <% @charities.each do |charity| %>
          <div class="settings-unit">
            <div class="settings-flex">
              <%= link_to charity_path(charity) do %>
                <%= cl_image_tag charity.photo, crop: :fill, class: "charity-avatar-xtra-small" %>
              <% end %>
              <%= link_to charity_path(charity) do %>
                <div class="settings-unit-name">
                  <%= charity.name %>
                </div>
              <% end %>
            </div>
            <i class="fas fa-dove settings-unit-icon"></i>
          </div>
        <% end %>
      </div>
    </div>
    <div class="pigeon-settings-devider">
      <div class="pigeon-settings-container">
        <div class="pigeon-settings-title">
          <i class="fas fa-user-friends settings-credit-icon"></i>
          <div>Follow friends</div>
        </div>
        <div class="settings-flex">
          <div class="pigeon-button-blue pigeon-button-large pigeon-button-width">Search</div>
        </div>
      </div>
      <div class="settings-units-container">
        <% @users.each do |user| %>
          <div class="settings-unit">
            <div class="settings-flex">
              <%= link_to user_path(user) do %>
                <%= cl_image_tag user.photo, crop: :fill, class: "charity-avatar-xtra-small" %>
              <% end %>
              <%= link_to user_path(user) do %>
                <div class="settings-unit-name">
                  <%= user.first_name %> <%= user.last_name %>
                </div>
              <% end %>
            </div>
            <i class="fas fa-dove settings-unit-icon"></i>
          </div>
        <% end %>
      </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="pigeon-container-profile">
  <div class="charity-profile-header">
    <div class="charity-profile-profile">
      <div class="charity-profile-avatar">
        <%= cl_image_tag @user.photo, crop: :fill, class: "charity-avatar-large" %>
      </div>
      <div class="charity-profile-title">
        <p class="charity-profile-category invisible">invisible</p>
        <h3 class="charity-profile-name"><%= @user.first_name %> <%= @user.last_name %></h3>
        <p class="charity-profile-category invisible">invisible</p>
      </div>
    </div>
    <div class="charity-profile-followers-display">
      <i class="fas fa-dove charity-profile-follower-item"></i>
      <div class="charity-profile-followers">1,500</div>
    </div>
  </div>
  <div class="charity-profile-action">
    <% unless @user == current_user  %>
      <div class="pigeon-button-large pigeon-button-gray" id="charity-profile-button-offset">Follow</div>
    <% end %>
  </div>
  <div class="charity-tabs">
    <a class="charity-tab active" id="charity-posts-tab" href="#">
      <p>Activity</p>
    </a>
    <a class="charity-tab" id="charity-about-tab" href="#">
      <p>Following</p>
    </a>
    <a class="charity-tab" id="charity-contact-tab" href="#">
      <p>Followers</p>
    </a>
  </div>
  <div class="charity-pages-container">

  </div>
</div>