config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    collection do
      get :settings
      get :preferences
    end
  end

  resources :charities do
    resources :posts, only: [:new, :create]
  end

  resources :comments, only: [ :create, :update, :destroy]
  resources :donations, only: [ :create]
  resources :follows, only: [ :create, :update]
  resources :likes, only: [ :create, :update]
  resources :posts, only: [ :new, :create, :edit, :update, :index]
  resources :ratings, only: [ :create, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charity.rb
class Charity < ApplicationRecord
  belongs_to :user
  has_many :donations
  has_many :follows
  has_many :ratings
  has_many :posts
  validates :name, presence: true, uniqueness: true
  mount_uploader :photo, PhotoUploader
  has_many :charity_themes, through: :charity_theme_relations
  has_many :charity_types, through: :charity_type_relations
end

app/models/charity_theme.rb
class CharityTheme < ApplicationRecord
  has_many :charity_theme_relations
  has_many :charity_theme_preferences
  has_many :charities, through: :charity_theme_relations
  has_many :users, through: :charity_theme_preferences
end

app/models/charity_theme_relation.rb
class CharityThemeRelation < ApplicationRecord
  belongs_to :charity
  belongs_to :charity_theme
end

app/models/charity_type.rb
class CharityType < ApplicationRecord
  has_many :charity_type_relations
  has_many :charity_type_preferences
  has_many :charities, through: :charity_type_relations
  has_many :users, through: :charity_type_preferences
end

app/models/charity_type_relation.rb
class CharityTypeRelation < ApplicationRecord
  belongs_to :charity
  belongs_to :charity_type
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :content, presence: true
end

app/models/controller.rb
class Controller < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :user
  belongs_to :charity
  validates :credit, presence: true
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :user
  belongs_to :charity

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :charity
  mount_uploader :photo, PhotoUploader
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :charity
  validates :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[facebook]
  has_many :donations
  has_many :follows
  has_many :ratings
  has_many :likes
  has_many :comments
  mount_uploader :photo, PhotoUploader
  has_many :charity_type_preferences
  has_many :charity_theme_preferences
  has_many :charity_types, through: :charity_type_preferences
  has_many :charity_themes, through: :charity_theme_preferences

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name   # assuming the user model has a name
      user.photo = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
      user.save!
    end
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new()
    @charity = Charity.find(params)
  end

  def create
    @post = Post.new(post_params)
    @charity = Charity.find(params[:charity_id])
    @post.charity = @charity
    @post.save
    redirect_to charity_path(@charity)
  end

  private

  def post_params
    params.require(:post).permit(:content, :photo)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def settings
    @user = current_user
    @users = User.all
    @charities = Charity.all
  end

  def preferences
    @themes = CharityTheme.all
    @types = CharityType.all
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    @user.save
    redirect_to posts_path
  end

  private

  def user_params
    params.require(:user).permit(:charity_theme_ids => [], :charity_type_ids => [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- <script src="https://unpkg.com/masonry-layout@4.2.2/dist/masonry.pkgd.min.js"></script> -->
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <h1>This is a h1 header</h1>
  <h2>This is a h1 header</h2>
  <h3>This is a h1 header</h3>
  <h3>This is a paragraph</h3>

  <div class="card-container">
    <div class="row">

      <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
        <div class="card">
          <div class="card-category">NGO</div>
          <div class="card-description">
            <h2>Broederlijk delen</h2>
            <p>Description</p>
          </div>
          <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay">
          <a class="card-link" href="#" ></a>
        </div>
      </div>

      <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
        <div class="card">
          <div class="card-category">NGO</div>
          <div class="card-description">
            <h2>Broederlijk delen</h2>
            <p>Description</p>
          </div>
          <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay">
          <a class="card-link" href="#" ></a>
        </div>
      </div>

      <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
        <div class="card">
          <div class="card-category">NGO</div>
          <div class="card-description">
            <h2>Broederlijk delen</h2>
            <p>Description</p>
          </div>
          <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay">
          <a class="card-link" href="#" ></a>
        </div>
      </div>

      <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
        <div class="card">
          <div class="card-category">NGO</div>
          <div class="card-description">
            <h2>Broederlijk delen</h2>
            <p>Description</p>
          </div>
          <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay">
          <a class="card-link" href="#" ></a>
        </div>
      </div>

    </div>
  </div>

  <div class="pigeon-container-white">
    <div class="button-holder">
      <p class="pigeon-button-small">Small button</p>
      <p class="pigeon-button-medium">Medium button</p>
      <p class="pigeon-button-large">Large button</p>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<!-- <ul class="facebook" role="navigation">
    <li class="facebook__brand"><i class="fas fa-dove"></i></li>
    <li class="facebook__search"><form><input placeholder="search for charity"/><i class="fa fa-search"></i></form></li>
    <li><i class="fa fa-user-circle-o"></i></li>
    <li><i class="fas fa-bell"></i>Notifications</li>
    <li><i class="fas fa-user-circle"></i>Steven</li>
    <li><i class="fa fa-caret-down"></i></li>
</ul>
 -->
<div class="pigeon-container-nav">
  <div class="container">
    <div class="topnav">
      <div class="creditnav">
        <i class="fas fa-hand-holding-heart navbar-item"></i>
        <div class="credits-display">1,500</div>
      </div>

      <div class="navbar-avatar">
        <% unless current_user.nil? %>
          <%= link_to user_path(current_user) do %>
            <% if current_user.nil? %>
              <%= image_tag 'http://www.travelcontinuously.com/wp-content/uploads/2018/04/empty-avatar.png',class: "avatar" %>
            <% elsif current_user.photo.blank? %>
              <%= image_tag 'http://www.travelcontinuously.com/wp-content/uploads/2018/04/empty-avatar.png',class: "avatar" %>
            <% else %>
              <%= cl_image_tag current_user.photo, crop: :fill, class: "avatar" %>
            <% end %>
          <% end %>
        <% end %>
      </div>

      <div class="notification-menu navbar-wagon-item">
        <div class="dropdown">
          <i class="far fa-bell navbar-item"></i>
        </div>
        <div class="dropdown">
          <i class="fas fa-bars navbar-item dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown"></i>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to posts_path do %>
                <div>Dashboard</div>
              <% end %>
            </li>
            <li>
              <%= link_to settings_users_path do %>
                <div>Settings</div>
              <% end %>
            </li>
            <% if user_signed_in? %>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
                <% end %>
              </li>
            <% else %>
              <li><a href="#">Log in</a></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>